# Generated by Django 5.2.4 on 2025-08-03 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_add_book', 'Can add a new book'), ('can_change_book', 'Can change an existing book'), ('can_delete_book', 'can delete a book'))},
        ),
    ]
